create table "public"."category_tags" (
    "id" bigint generated by default as identity not null,
    "tag_name" text not null
);


create table "public"."emotional_impact_tags" (
    "id" bigint generated by default as identity not null,
    "tag_name" text not null
);


create table "public"."news_article_emotional_impact" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "news_article_sentiment_id" bigint,
    "emotional_impact_tag_id" bigint,
    "is_primary" boolean
);


create table "public"."news_article_sentiments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "news_article_id" bigint not null,
    "sentiment_label" text,
    "sentiment_confidence" integer,
    "clickbait_level" smallint,
    "version_info" jsonb
);


create table "public"."news_article_tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "category_tag_id" bigint,
    "is_primary" boolean,
    "news_article_sentiment_id" bigint
);


create table "public"."news_articles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "url" text not null,
    "description" text,
    "category" text not null,
    "media_url" text,
    "publish_date" timestamp with time zone,
    "content" text,
    "markdown_content" text,
    "html_content" text,
    "source" text not null,
    "hidden" boolean
);


CREATE UNIQUE INDEX article_tags_pkey ON public.news_article_tags USING btree (id);

CREATE UNIQUE INDEX category_tags_pkey ON public.category_tags USING btree (id);

CREATE UNIQUE INDEX category_tags_tag_name_key ON public.category_tags USING btree (tag_name);

CREATE UNIQUE INDEX emotional_impact_tags_pkey ON public.emotional_impact_tags USING btree (id);

CREATE UNIQUE INDEX emotional_impact_tags_tag_name_key ON public.emotional_impact_tags USING btree (tag_name);

CREATE INDEX idx_na_publish_date_id_desc ON public.news_articles USING btree (publish_date DESC, id DESC);

CREATE INDEX idx_na_source ON public.news_articles USING btree (source text_pattern_ops);

CREATE INDEX idx_naei_sentiment_primary_emotion ON public.news_article_emotional_impact USING btree (news_article_sentiment_id, emotional_impact_tag_id, is_primary) WHERE (is_primary = true);

CREATE INDEX idx_nas_sentiment_label ON public.news_article_sentiments USING btree (sentiment_label text_pattern_ops);

CREATE INDEX idx_nat_sentiment_primary_category ON public.news_article_tags USING btree (news_article_sentiment_id, category_tag_id, is_primary) WHERE (is_primary = true);

CREATE UNIQUE INDEX news_article_emotional_impact_pkey ON public.news_article_emotional_impact USING btree (id);

CREATE UNIQUE INDEX news_article_sentiments_pkey ON public.news_article_sentiments USING btree (id);

CREATE UNIQUE INDEX news_articles_pkey ON public.news_articles USING btree (id);

CREATE UNIQUE INDEX news_articles_url_key ON public.news_articles USING btree (url);

alter table "public"."category_tags" add constraint "category_tags_pkey" PRIMARY KEY using index "category_tags_pkey";

alter table "public"."emotional_impact_tags" add constraint "emotional_impact_tags_pkey" PRIMARY KEY using index "emotional_impact_tags_pkey";

alter table "public"."news_article_emotional_impact" add constraint "news_article_emotional_impact_pkey" PRIMARY KEY using index "news_article_emotional_impact_pkey";

alter table "public"."news_article_sentiments" add constraint "news_article_sentiments_pkey" PRIMARY KEY using index "news_article_sentiments_pkey";

alter table "public"."news_article_tags" add constraint "article_tags_pkey" PRIMARY KEY using index "article_tags_pkey";

alter table "public"."news_articles" add constraint "news_articles_pkey" PRIMARY KEY using index "news_articles_pkey";

alter table "public"."category_tags" add constraint "category_tags_tag_name_key" UNIQUE using index "category_tags_tag_name_key";

alter table "public"."emotional_impact_tags" add constraint "emotional_impact_tags_tag_name_key" UNIQUE using index "emotional_impact_tags_tag_name_key";

alter table "public"."news_article_emotional_impact" add constraint "news_article_emotional_impact_emotional_impact_tag_id_fkey" FOREIGN KEY (emotional_impact_tag_id) REFERENCES emotional_impact_tags(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_article_emotional_impact" validate constraint "news_article_emotional_impact_emotional_impact_tag_id_fkey";

alter table "public"."news_article_emotional_impact" add constraint "news_article_emotional_impact_news_article_sentiment_id_fkey" FOREIGN KEY (news_article_sentiment_id) REFERENCES news_article_sentiments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_article_emotional_impact" validate constraint "news_article_emotional_impact_news_article_sentiment_id_fkey";

alter table "public"."news_article_sentiments" add constraint "news_article_sentiments_article_fkey" FOREIGN KEY (news_article_id) REFERENCES news_articles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_article_sentiments" validate constraint "news_article_sentiments_article_fkey";

alter table "public"."news_article_tags" add constraint "news_article_tags_category_tag_id_fkey" FOREIGN KEY (category_tag_id) REFERENCES category_tags(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_article_tags" validate constraint "news_article_tags_category_tag_id_fkey";

alter table "public"."news_article_tags" add constraint "news_article_tags_news_article_sentiment_id_fkey" FOREIGN KEY (news_article_sentiment_id) REFERENCES news_article_sentiments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."news_article_tags" validate constraint "news_article_tags_news_article_sentiment_id_fkey";

alter table "public"."news_articles" add constraint "news_articles_url_key" UNIQUE using index "news_articles_url_key";

grant delete on table "public"."category_tags" to "anon";

grant insert on table "public"."category_tags" to "anon";

grant references on table "public"."category_tags" to "anon";

grant select on table "public"."category_tags" to "anon";

grant trigger on table "public"."category_tags" to "anon";

grant truncate on table "public"."category_tags" to "anon";

grant update on table "public"."category_tags" to "anon";

grant delete on table "public"."category_tags" to "authenticated";

grant insert on table "public"."category_tags" to "authenticated";

grant references on table "public"."category_tags" to "authenticated";

grant select on table "public"."category_tags" to "authenticated";

grant trigger on table "public"."category_tags" to "authenticated";

grant truncate on table "public"."category_tags" to "authenticated";

grant update on table "public"."category_tags" to "authenticated";

grant delete on table "public"."category_tags" to "service_role";

grant insert on table "public"."category_tags" to "service_role";

grant references on table "public"."category_tags" to "service_role";

grant select on table "public"."category_tags" to "service_role";

grant trigger on table "public"."category_tags" to "service_role";

grant truncate on table "public"."category_tags" to "service_role";

grant update on table "public"."category_tags" to "service_role";

grant delete on table "public"."emotional_impact_tags" to "anon";

grant insert on table "public"."emotional_impact_tags" to "anon";

grant references on table "public"."emotional_impact_tags" to "anon";

grant select on table "public"."emotional_impact_tags" to "anon";

grant trigger on table "public"."emotional_impact_tags" to "anon";

grant truncate on table "public"."emotional_impact_tags" to "anon";

grant update on table "public"."emotional_impact_tags" to "anon";

grant delete on table "public"."emotional_impact_tags" to "authenticated";

grant insert on table "public"."emotional_impact_tags" to "authenticated";

grant references on table "public"."emotional_impact_tags" to "authenticated";

grant select on table "public"."emotional_impact_tags" to "authenticated";

grant trigger on table "public"."emotional_impact_tags" to "authenticated";

grant truncate on table "public"."emotional_impact_tags" to "authenticated";

grant update on table "public"."emotional_impact_tags" to "authenticated";

grant delete on table "public"."emotional_impact_tags" to "service_role";

grant insert on table "public"."emotional_impact_tags" to "service_role";

grant references on table "public"."emotional_impact_tags" to "service_role";

grant select on table "public"."emotional_impact_tags" to "service_role";

grant trigger on table "public"."emotional_impact_tags" to "service_role";

grant truncate on table "public"."emotional_impact_tags" to "service_role";

grant update on table "public"."emotional_impact_tags" to "service_role";

grant delete on table "public"."news_article_emotional_impact" to "anon";

grant insert on table "public"."news_article_emotional_impact" to "anon";

grant references on table "public"."news_article_emotional_impact" to "anon";

grant select on table "public"."news_article_emotional_impact" to "anon";

grant trigger on table "public"."news_article_emotional_impact" to "anon";

grant truncate on table "public"."news_article_emotional_impact" to "anon";

grant update on table "public"."news_article_emotional_impact" to "anon";

grant delete on table "public"."news_article_emotional_impact" to "authenticated";

grant insert on table "public"."news_article_emotional_impact" to "authenticated";

grant references on table "public"."news_article_emotional_impact" to "authenticated";

grant select on table "public"."news_article_emotional_impact" to "authenticated";

grant trigger on table "public"."news_article_emotional_impact" to "authenticated";

grant truncate on table "public"."news_article_emotional_impact" to "authenticated";

grant update on table "public"."news_article_emotional_impact" to "authenticated";

grant delete on table "public"."news_article_emotional_impact" to "service_role";

grant insert on table "public"."news_article_emotional_impact" to "service_role";

grant references on table "public"."news_article_emotional_impact" to "service_role";

grant select on table "public"."news_article_emotional_impact" to "service_role";

grant trigger on table "public"."news_article_emotional_impact" to "service_role";

grant truncate on table "public"."news_article_emotional_impact" to "service_role";

grant update on table "public"."news_article_emotional_impact" to "service_role";

grant delete on table "public"."news_article_sentiments" to "anon";

grant insert on table "public"."news_article_sentiments" to "anon";

grant references on table "public"."news_article_sentiments" to "anon";

grant select on table "public"."news_article_sentiments" to "anon";

grant trigger on table "public"."news_article_sentiments" to "anon";

grant truncate on table "public"."news_article_sentiments" to "anon";

grant update on table "public"."news_article_sentiments" to "anon";

grant delete on table "public"."news_article_sentiments" to "authenticated";

grant insert on table "public"."news_article_sentiments" to "authenticated";

grant references on table "public"."news_article_sentiments" to "authenticated";

grant select on table "public"."news_article_sentiments" to "authenticated";

grant trigger on table "public"."news_article_sentiments" to "authenticated";

grant truncate on table "public"."news_article_sentiments" to "authenticated";

grant update on table "public"."news_article_sentiments" to "authenticated";

grant delete on table "public"."news_article_sentiments" to "service_role";

grant insert on table "public"."news_article_sentiments" to "service_role";

grant references on table "public"."news_article_sentiments" to "service_role";

grant select on table "public"."news_article_sentiments" to "service_role";

grant trigger on table "public"."news_article_sentiments" to "service_role";

grant truncate on table "public"."news_article_sentiments" to "service_role";

grant update on table "public"."news_article_sentiments" to "service_role";

grant delete on table "public"."news_article_tags" to "anon";

grant insert on table "public"."news_article_tags" to "anon";

grant references on table "public"."news_article_tags" to "anon";

grant select on table "public"."news_article_tags" to "anon";

grant trigger on table "public"."news_article_tags" to "anon";

grant truncate on table "public"."news_article_tags" to "anon";

grant update on table "public"."news_article_tags" to "anon";

grant delete on table "public"."news_article_tags" to "authenticated";

grant insert on table "public"."news_article_tags" to "authenticated";

grant references on table "public"."news_article_tags" to "authenticated";

grant select on table "public"."news_article_tags" to "authenticated";

grant trigger on table "public"."news_article_tags" to "authenticated";

grant truncate on table "public"."news_article_tags" to "authenticated";

grant update on table "public"."news_article_tags" to "authenticated";

grant delete on table "public"."news_article_tags" to "service_role";

grant insert on table "public"."news_article_tags" to "service_role";

grant references on table "public"."news_article_tags" to "service_role";

grant select on table "public"."news_article_tags" to "service_role";

grant trigger on table "public"."news_article_tags" to "service_role";

grant truncate on table "public"."news_article_tags" to "service_role";

grant update on table "public"."news_article_tags" to "service_role";

grant delete on table "public"."news_articles" to "anon";

grant insert on table "public"."news_articles" to "anon";

grant references on table "public"."news_articles" to "anon";

grant select on table "public"."news_articles" to "anon";

grant trigger on table "public"."news_articles" to "anon";

grant truncate on table "public"."news_articles" to "anon";

grant update on table "public"."news_articles" to "anon";

grant delete on table "public"."news_articles" to "authenticated";

grant insert on table "public"."news_articles" to "authenticated";

grant references on table "public"."news_articles" to "authenticated";

grant select on table "public"."news_articles" to "authenticated";

grant trigger on table "public"."news_articles" to "authenticated";

grant truncate on table "public"."news_articles" to "authenticated";

grant update on table "public"."news_articles" to "authenticated";

grant delete on table "public"."news_articles" to "service_role";

grant insert on table "public"."news_articles" to "service_role";

grant references on table "public"."news_articles" to "service_role";

grant select on table "public"."news_articles" to "service_role";

grant trigger on table "public"."news_articles" to "service_role";

grant truncate on table "public"."news_articles" to "service_role";

grant update on table "public"."news_articles" to "service_role";


